# Révision 1 : la bibliothèque Numpy

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/512px-NumPy_logo_2020.svg.png" alt="numpy" width="400"/>

#### [Pierre-Loic BAYART](https://www.linkedin.com/in/pierreloicbayart/) - Formation développeur d'applications spécialisation data analyst - Webforce3 - Grenoble Ecole de Management

## Création de tableaux Numpy

- **Import** de la bibliothèque avec son **alias** et vérification de la **version**

In [1]:
import numpy as np
print(np.__version__)

1.23.5


- Création d'un tableau Numpy à partir d'une **liste Python**

In [2]:
array_1 = np.array([1, 8, 9])
array_1, array_1.dtype, array_1.nbytes

(array([1, 8, 9]), dtype('int32'), 12)

In [3]:
array_1 = np.array([1, 8, 9], dtype="int16")
array_1, array_1.dtype, array_1.nbytes

(array([1, 8, 9], dtype=int16), dtype('int16'), 6)

In [4]:
# Typage le plus contraignant
arr = np.array([1, 2, 3.0])
arr, arr.dtype

(array([1., 2., 3.]), dtype('float64'))

- Création de **tableau Numpy** à partir de **fonctions Numpy**

In [5]:
# Tableau de 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
# Tableau de 1
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# Tableau de 1 de même dimension (existe aussi empty_like, zeros_like, full_like)
zero = np.zeros(5)
zero, np.ones_like(zero)

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [8]:
# Tableau non initialisé (petit gain de temps à la création)
np.empty((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Tableau de constantes
np.full((3, 5), 10.5)

array([[10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5]])

In [10]:
# Tableau de nombres aléatoires uniforme entre 0 et 1
np.random.random((3, 3))

array([[0.54587679, 0.11011045, 0.18083963],
       [0.30286428, 0.6877064 , 0.64831136],
       [0.2564825 , 0.00602657, 0.25785916]])

In [11]:
# Tableau de nombres aléatoires loi normale
np.random.randn(3)

array([-1.38499665,  0.09835093, -0.12441976])

In [12]:
# Tableau de nombres aléatoires uniforme entre deux bornes
np.random.randint(3, 10, size=6)

array([6, 8, 3, 3, 5, 7])

In [13]:
# Matrice identité
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# Suite de nombres entiers (comme range en Python standard)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
# Suite de nombres espacés uniformément
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Propriétés des tableaux Numpy

In [16]:
data = np.random.random((3, 3, 2))
data

array([[[0.1504547 , 0.6987096 ],
        [0.51492037, 0.25273601],
        [0.42129869, 0.78363255]],

       [[0.60019616, 0.23827322],
        [0.264075  , 0.49465843],
        [0.71496203, 0.63001784]],

       [[0.61667011, 0.46909905],
        [0.12372677, 0.00441394],
        [0.44961723, 0.83273682]]])

In [17]:
print(f"Nombre de dimensions : {data.ndim}")
print(f"Taille de chaque dimension : {data.shape}")
print(f"Nombre d'élèments au total : {data.size}")
print(f"Type de données : {data.dtype}")

Nombre de dimensions : 3
Taille de chaque dimension : (3, 3, 2)
Nombre d'élèments au total : 18
Type de données : float64


## Indexation et slicing des tableaux Numpy

L'**indexation** et le **slicing** de tableaux Numpy s'effectuent **comme avec les listes Python**

In [18]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
print(f"Premier élément : {arr[0]}")
print(f"Dernier élément : {arr[-1]}")
print(f"Tableau à partir du troisième élément : {arr[2:]}")

Premier élément : 0
Dernier élément : 9
Tableau à partir du troisième élément : [2 3 4 5 6 7 8 9]


## ✏️ Exercice

Transformer la **matrice identité 5x5** en une **croix de 1** (ajout de la seconde diagonale)

In [20]:
arr = np.eye(5)
for i in range(5):
    arr[i,-i-1] = 1
arr

array([[1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [21]:
np.logical_or(np.eye(5),np.eye(5)[::-1]).astype("int")

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

## Concaténation de tableaux Numpy

Ressources :

- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
- https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
- https://numpy.org/doc/stable/reference/generated/numpy.vstack.html

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.vstack([a, b])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.hstack([a, b.T])

## Masques booléens

Ressources :

- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
x = np.random.rand(5, 3)
x

In [ ]:
x > 0.8

In [ ]:
x[x > 0.8]

In [ ]:
np.where(x > 0.8)

## Calculs sur les tableaux Numpy

In [ ]:
# Multiplication par un scalaire
arr = np.arange(10)
arr * 10

In [ ]:
# Division par un scalaire
arr = np.arange(10)
arr / 10

In [ ]:
# Addition d'un scalaire
arr = np.arange(10)
arr + 10

In [ ]:
# Soustraction d'un scalaire
arr = np.arange(10)
arr - 10

In [ ]:
# Modulo
arr = np.arange(10)
arr % 3

In [ ]:
arr_1 = np.arange(10)
arr_2 = np.arange(10, 20)
arr_1, arr_2

In [ ]:
# Multiplication de deux tableaux
arr_1 * arr_2

In [ ]:
# Division de deux tableaux
arr_1 / arr_2

In [ ]:
# Addition de deux tableaux
arr_1 + arr_2

In [ ]:
# Soustraction de deux tableaux
arr_1 - arr_2

In [ ]:
arr_1 = np.ones((2, 3))
arr_2 = np.arange(6).reshape((3, 2))
arr_1, arr_2

In [ ]:
# Produit matriciel
np.dot(arr_1, arr_2)

In [ ]:
# Produit matriciel
arr_1 @ arr_2

## 🏅 Exercice bilan

**Calculer manuellement la trace** (somme des élèments diagonaux) de la matrice suivante. Vérifier à l'aide de la function [numpy.trace](https://numpy.org/doc/stable/reference/generated/numpy.trace.html)

In [22]:
matrix = np.array([
        [12, 8, 7],
        [7, 15, 16],
        [-1, 32, -8],
])

In [23]:
trace = 0
for i in range(matrix.shape[0]):
    trace += matrix[i, i]
print(trace)

19


In [25]:
sum([matrix[i, i] for i in range(matrix.shape[0])])

19

In [24]:
np.trace(matrix)

19